pipelines:
  ArtifactoryPlugin-BuildAndPublish:
    group: GoCD-Plugins
    materials:
      mygit:
        git: git@github.com:stone-payments/go-artifactory-plugin.git
    stages:
      - BuildAndPublish:
          clean_workspace: true
          jobs:
            build:
              elastic_profile_id: docker.java7-maven            
              tasks:
                exec:
                  command: mvn
                  arguments:
                    - package                          
                plugin:
                  options:
                    URI: gocd-plugins/publish-to-artifactory
                    uriIsFolder: true
                    Path: target/dist/*.jar
                    Properties: buildtool=gocd
                  configuration:
                    id: com.tw.go.plugins.go-artifactory-plugin
                    version: 1.0.0 
                  run_if: passed